apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myeks-1
  region: ap-south-1
vpc:
  id: "vpc-01102866efa4ca413"
  subnets:
    public:
      ap-south-1a:
          id: "subnet-0ef1b1daf209c3219"
      ap-south-1b:
          id: "subnet-0c59c7296c7fda3e2"
      ap-south-1c:
          id: "subnet-0faa67c6b3136f501"
managedNodeGroups:
  - name: eks-node-1
    instanceType: t2.micro
    minSize: 1
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
    ssh: 
      publicKeyName: eks-ec2

  - name: windows-node-1
    amiFamily: WindowsServer2019CoreContainer
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    instanceType: t2.small

    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        imageBuilder: true 
        appMesh: true
        albIngress: true