apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myeks-1
  region: ap-south-1
  
vpc:
  id: "vpc-0dd54cac4c5d5b26f"
  subnets:
    public:
      ap-south-1a:
          id: "subnet-086037268645555f1"
      ap-south-1b:
          id: "subnet-04971a7a04b0fd981"
      ap-south-1c:
          id: "subnet-0f5aaa77f5986c289"
    private:
      ap-south-1a:
          id: "subnet-0ccb059dfa0c65a7f"
      ap-south-1b:
          id: "subnet-0ffa64ab1deedb8d1"
      ap-south-1c:
          id: "subnet-0f41827c7d4009ccc"

managedNodeGroups:
  - name: eks-node-1
    instanceType: t2.micro
    minSize: 1
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
    ssh: 
      publicKeyName: eks-ec2

  - name: windows-node-1
    amiFamily: WindowsServer2019CoreContainer
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    instanceType: t2.small

    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        imageBuilder: true 
        appMesh: true
        albIngress: true