apiVersion: v1
kind: Service
metadata:
  name: httpd-nodeport-service  # Name of the Service
spec:
  type: NodePort
  selector:
  # Loadbalance traffic across Pods matching this label selector
    app: httpd
  # Accept traffic sent to port 80    
  ports: 
    - name: http
      port: 82    # Service Port
      targetPort: 80 # Container Port
      nodePort: 31233 # NodePort