apiVersion: v1
kind: Service
metadata:
  name: kubenginx-nodeport-service  # Name of the Service
spec:
  type: NodePort
  selector:
  # Loadbalance traffic across Pods matching this label selector
    app: kubenginx
  # Accept traffic sent to port 80    
  ports: 
    - name: http
      port: 81    # Service Port
      targetPort: 80 # Container Port
      nodePort: 31232 # NodePort