apiVersion: v1 
kind: Pod  
metadata:
  name: kubenginx
  labels: 
    app: kubenginx         
spec:
  containers: 
    - name: kubenginx
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80