apiVersion: v1
kind: LimitRange

metadata:
  name: default-cpu-memory-range
  region: dev1

spec:
  limit:
    - default:
        memory: "512Mi"
        cpu: "500m"
      defaultRequest:
        memory: "256Mi"
        cpu: "300m"
      type: Container
    