apiVersion: v1
kind: Service
metadata:
  name: windows-iis
  namespace: windows
  labels:
    app: windows-iis
spec:
  type: NodePort
  selector:
    app: windows-iis
  ports:
    - protocol: TCP
      port: 88
      targetPort: 80