apiVersion: v1
kind: Service
metadata:
  name: windows-iis
  namespace: eks-windows-apps
  labels:
    app: windows-iis
spec:
  selector:
    app: windows-iis
  ports:
    - protocol: TCP
      port: 88
      targetPort: 80