apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myeks
  region: ap-south-1

vpc:
  id: "vpc-08e0cf6d6450d84ea"
  subnets:
    private:
      ap-south-1a:
          id: "subnet-0055657f3cfdb4ad5"
      ap-south-1b:
          id: "subnet-008cee3905b8e1dd4"

managedNodeGroups:
  - name: EKS-Linux-NG
    instanceType: t2.micro
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: true
    ssh: 
      publicKeyName: eks-ec2

    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        imageBuilder: true
        appMesh: true
        albIngress: true