apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myeks-1
  region: ap-south-1

vpc:
  id: "vpc-098de665726ddf1cb"
  subnets:
    private:
      ap-south-1a:
          id: "subnet-0a8e9a07ff82144cc"
      ap-south-1b:
          id: "subnet-0b76af49083a70abf"

managedNodeGroups:
  - name: EKS-Linux-NG
    instanceType: t2.micro
    minSize: 1
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: true
    ssh: 
      publicKeyName: eks-ec2

    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        imageBuilder: true
        appMesh: true
        albIngress: true