apiVersion: v1
kind: Service
metadata:
  name: httpd-loadbalancer-service  # Name of the Service
spec:
  type: LoadBalancer
  selector:
  # Loadbalance traffic across Pods matching this label selector
    app: httpd
  # Accept traffic sent to port 80    
  ports: 
    - name: http
      protocal: TCP
      port: 80   # Service Port
      targetPort: 80 # Container Port
      